cli/src/rust_template.rs
| Hold | Feature/Bug | No | - |
- The component template was adding the Copy traits, which is not implemented for Strings
- Removed the Copy trait and added an example with String in the generated template
=> :sparkles: Add strings to the template

.github/workflows/run-tests.yml, Cargo.lock, cli/Cargo.toml, cli/src/lib.rs, cli/src/rust_template.rs, crates/bolt-lang/Cargo.toml
| Hold | Feature  | No | #5  |
Complex to setup the ECS and interaction with the World program
- On Init, create a minimal working example with one Component and one System
- Anchor.toml specify the accounts that needs to be cloned in the local validator 
- Fix `--version` command
- Enable the `--force` flag to init over existing folders
- Remove `-n` from the `component` and `systems` command. E.g.: creating a component now can be done with `bolt component new-component`
- Add tests for the CLI. Added a workflow to install it, create a new-project and run the tests of the new project
Depends on https://github.com/coral-xyz/anchor/pull/2785 for defining workspace members
```yaml
[workspace]
members = [ …
```
=> :sparkles: Add a working ecs example on project init

Anchor.toml, Cargo.lock, cli/Cargo.toml, cli/src/lib.rs, cli/src/rust_template.rs, crates/bolt-lang/attribute/component-deserialize/src/lib.rs, crates/bolt-lang/attribute/system-input/src/lib.rs, crates/bolt-lang/src/lib.rs, crates/types/Cargo.toml, crates/types/src/component_Fn1JzzEdyb55fsyduWS94mYHizGhJZuhvjX6DVvrmGbQ.rs, crates/types/src/lib.rs, examples/system-simple-movement/Cargo.toml, examples/system-simple-movement/src/lib.rs
| Status | Type     | ⚠️ Core Change | Issue |
|:------:|:--------:|:---------------:|:-----:|
| Ready  | Feature  | Yes             | #23   |
Composability on Solana is currently limited by the fact that typically crates must be available in order to interact with a program. Although Rust crates can be generated automatically if the IDL is published, this process is usually time-consuming and error-prone, as the crates could become outdated. Furthermore, the ECS pattern offers a way to structure logic in a very decoupled way, where common data structures (components) can be reused within or outside a project. This also allows anyone to write or propose logic (system) very easily. Therefore, having a simple way to use components/accounts in a new program is essential to promote …
=> :sparkles: Dynamic types resolver

cli/src/rust_template.rs, crates/bolt-helpers/attribute/system-template/src/lib.rs, crates/bolt-helpers/attribute/world-apply/src/lib.rs, crates/bolt-lang/attribute/bolt-program/src/lib.rs, crates/bolt-lang/attribute/system-input/src/lib.rs, examples/system-apply-velocity/src/lib.rs, programs/bolt-component/src/lib.rs, programs/bolt-system/src/lib.rs, programs/world/src/lib.rs, tests/bolt.ts
| Ready | Feature | Yes | #6  |
See #6 
All systems can access the signing authority with `ctx.accounts.authority`
Closes #6
=> :sparkles: Propagate signing authority to the systems

.github/workflows/run-tests.yml, cli/src/rust_template.rs, crates/bolt-lang/attribute/component/src/lib.rs, examples/component-position/src/lib.rs, examples/component-velocity/src/lib.rs
| Ready | Feature/Refactor | Yes| #4  |
Difficult to override defaults, `Derive(Default)` implicitly added by the macro 
Components now explicitly derive Default, so that it could be implemented alternatively:
e.g.
```rust
#[component]
#[derive(Copy)]
pub struct Position {
pub x: i64,
pub y: i64,
pub z: i64,
}
impl Default for Position {
fn default() -> Self {
Self {
x: 100,
y: 0,
z: 0,
bolt_metadata: BoltMetadata::default(),
}
}
}
```
Closes #4
=> :adhesive_bandage: Explicit Default in components to allow custom defaults

crates/bolt-lang/attribute/component-deserialize/src/lib.rs, crates/bolt-lang/attribute/component/src/lib.rs, crates/types/src/component_Fn1JzzEdyb55fsyduWS94mYHizGhJZuhvjX6DVvrmGbQ.rs
| Ready | Feature/Refactor | No | - |
component_deserialize tipically used with `copy` and `clone` derives 
Automatically add `copy` and `clone` derive when using component_deserialize
Add a `new` constructor which allows to build component without `bolt_metadata` field
=> :sparkles: Simplify component_deserialize macro

.github/workflows/publish-bolt-crates.yml, Cargo.lock, Cargo.toml, cli/src/rust_template.rs, crates/bolt-lang/Cargo.toml, crates/bolt-lang/attribute/arguments/Cargo.toml, crates/bolt-lang/attribute/arguments/src/lib.rs, crates/bolt-lang/attribute/component/src/lib.rs, crates/bolt-lang/attribute/system/src/lib.rs, crates/bolt-lang/src/lib.rs, examples/system-simple-movement/Cargo.toml, examples/system-simple-movement/src/lib.rs
| Ready | Feature | No | - |
- Arguments in a systems are always of type `Vec<u8>`, this allows to maintain a standard function signature and easily call from the central proxy program
- System macro now allows to define serializable types and automatically parse and convert them
=> :sparkles: Simplify system arguments

.github/workflows/publish-bolt-crates.yml, .github/workflows/publish-bolt-sdk.yml, .github/workflows/run-tests.yml, Cargo.lock, Cargo.toml, cli/Cargo.toml, cli/src/lib.rs, cli/src/rust_template.rs, crates/bolt-lang/Cargo.toml, crates/types/Cargo.toml, examples/system-simple-movement/Cargo.toml, package-lock.json, package.json, tests/bolt.ts, yarn.lock
| Ready | Feature/Refactor | No | #44  |
_What problem are you trying to solve?_
Upgraded to anchor_lang [0.30.0](https://github.com/coral-xyz/anchor/releases/tag/v0.30.0) and replaced custom packaged version which was previously used to access the newest IDL standard
Closes #44
=> :arrow_up: Upgrade anchor_lang to 0.30.0

.github/workflows/run-tests.yml, clients/bolt-sdk/README.md
| Ready| Bug/Tooling | No | -- |
When changing the Typescript files, yarn build was not running in the CI, leading to the CI's test succeeding even if we just introduced a bug.
Make the CI run `yarn build` before testing
=> fix: make sure CI is recompiling the /lib folder when we make changes

Cargo.lock, Cargo.toml, cli/src/lib.rs, crates/types/Cargo.toml, package.json, yarn.lock
| Ready | Feature | No | - |
Upgrade Anchor dependency to 0.30.1
=> :sparkles: Upgrade to Anchor 0.30.1

clients/bolt-sdk/src/world/transactions.ts
| Ready| Feature | No | -- |
Sometimes we want to build a single transaction that can create entities and components at the same time for example.
Just exposing the instructions in the typescript SDK so that user can build transactions manually
=> feat: expose instructions in API

.github/workflows/run-tests.yml
| Ready| fix | Yes| [Link](<Issue link here>) |
Contributor tests where failing when creating the **PR** from **Forked repository**.
Reason: https://github.com/magicblock-labs/bolt/pull/74#issuecomment-2296055732
Added the `pull_request_target` for fork repository also.
=> fix: secret ENV variables should be read by forked PR's also

clients/bolt-sdk/src/delegation/delegate.ts, tests/bolt.ts
| Ready| Feature | Yes/No | [Link](https://github.com/magicblock-labs/bolt/issues/67) |
There could be a bolt-specific wrapper for delegating a component (similar to InitializeComponent wrapper)
Added `DelegateComponent` wrapper function
cc - @crypto-vincent
Closes #67
=> feat: `DelegateComponent` wrapper function

.github/workflows/publish-bolt-crates.yml, .github/workflows/publish-bolt-sdk.yml, .github/workflows/run-tests.yml, Anchor.toml, Cargo.lock, cli/Cargo.toml, cli/src/instructions.rs, cli/src/lib.rs, clients/bolt-sdk/package.json, clients/bolt-sdk/src/generated/idl/world.json, clients/bolt-sdk/src/generated/index.ts, clients/bolt-sdk/src/generated/types/world.ts, clients/bolt-sdk/src/world/transactions.ts, crates/bolt-helpers/attribute/world-apply/src/lib.rs, programs/world/src/error.rs, programs/world/src/lib.rs, tests/bolt.ts
| Ready | Feature | Yes | #8  |
- Systems where completely permissionless
- Added a way to add/remove authorities authorities on a world instance
- Adde a mechanism to approve/remove systems allows in a specific game instance
See #8 for a full description 
Authorize a new authority
```bash
bolt authorize JBupPMmv4zaXa5c8EdubsCPvoHZwCK7mwnDfmfs8dC5Y tEsT3eV6RFCWs1BZ7AXTzasHqTtMnMLCB2tjQ42TDXD
```
Deauthorize an authority
```bash
bolt deauthorize JBupPMmv4zaXa5c8EdubsCPvoHZwCK7mwnDfmfs8dC5Y tEsT3eV6RFCWs1BZ7AXTzasHqTtMnMLCB2tjQ42TDXD
```
Approve an authority using a specific key
```bash
bolt authorize JBupPMmv4zaXa5c8EdubsCPvoHZwCK7mwnDfmfs8dC5Y tEsT3eV6RFCWs1BZ7AXTzasHqTtMnMLCB2tjQ42TDXD --provider.wallet …
```
=> feat: Add authority approval/removal for world instances

cli/src/templates/workspace.rs, clients/bolt-sdk/src/index.ts, package.json, tests/bolt.ts, yarn.lock
| Ready| Feature | No | [#61](https://github.com/magicblock-labs/bolt/issues/61) |
- When building the frontend of a BOLT application the users ends up having to have the whole of anchor as a direct dependency to parse the IDLs of the components/systems
- Re-export `@coral-xyz/anchor` from `bolt-sdk`
- Closes: #61
=> feat: :sparkles: Make sure frontend code doesn't need to depend on `anchor`

cli/src/templates/workspace.rs
`ApplySystem` now takes `world` as a parameter. The test template code wasn't updated to do so.
=> :recycle: Fixing test template, broken after code refactor

.prettierignore, cli/src/rust_template.rs, cli/src/templates/component/mod.rs, cli/src/templates/program/mod.rs, cli/src/templates/system/mod.rs, cli/src/templates/workspace/mod.rs, scripts/lint.sh, scripts/test.sh, tests/bolt.ts
| Ready| Tooling| No | None |
* ./scripts/test.sh is only runnable from project root.
* We don't have a lint script
* Code has lint errors
* Allow relative paths
* Implement ./scripts/lint.sh
* Fix lint errors
=> test: test and lint scripts

clients/bolt-sdk/src/generated/instructions/apply.ts, clients/bolt-sdk/src/world/transactions.ts, tests/bolt.ts
Original PR by @obstoody
| Ready| Feature | No | None |
I noticed that the `apply` function used in world programs was missing from the SDK, so I added it.
* Added `Apply` function in `sdk/world/transactions.ts` file.
* Fixed `createApplyInstruction` to take the world pda
* Added a test for it
=> feat: add missing apply function in sdk and add test for it

.github/workflows/publish-bolt-crates.yml, .github/workflows/publish-bolt-sdk.yml, .github/workflows/publish-packages.yml, CHANGELOG.md, Cargo.lock, Cargo.toml, cli/npm-package/package.json, cli/npm-package/package.json.tmpl, clients/bolt-sdk/package.json
| Ready | Release | No | None |
- Reorganizing templates, using bolt.workspace an… (#95)
- Fixing test template, broken after code refactor (#93)
=> release: v0.1.11

.github/workflows/publish-packages.yml, Cargo.lock, Cargo.toml, Cliff.toml, clients/bolt-sdk/package.json, crates/bolt-cli/npm-package/package.json, crates/bolt-cli/npm-package/package.json.tmpl, docs/CHANGELOG.md, scripts/version-align.sh
| Ready| Refactor| No | None |
- Refactor: re-exporting anchor-lang (#114)
- Refactor: files structure (#113)
=> release: v0.1.12

crates/bolt-lang/attribute/system/src/lib.rs
| Ready | Hotfix | No | None |
We cannot write `return Ok(ctx.accounts)` in inner blocks of the `execute` function.
Fix the #[system] proc-macro to recursively look for `return Ok(ctx.accounts)` and transform them to `return ctx.accounts.try_to_vec()`.
=> fix(system): fix system return statement in inner blocks

Cargo.lock, Cargo.toml, crates/types/Cargo.toml, examples/component-position/Cargo.toml, examples/component-velocity/Cargo.toml, examples/system-apply-velocity/Cargo.toml, examples/system-apply-velocity/src/lib.rs, examples/system-fly/Cargo.toml, examples/system-simple-movement/Cargo.toml
| Ready | Bug | No | None |
`anchor-spl 0.30.1` uses `spl-token-2022 3.0.4` that introduces this error:
```
Error: Function _ZN14spl_token_20229extension21confidential_transfer12verify_proof30verify_transfer_with_fee_proof17h1150fb2913991c8dE Stack offset of 4392 exceeded max offset of 4096 by 296 bytes, please minimize large stack variables. Estimated function frame size: 4472 bytes. Exceeding the maximum stack offset may cause undefined behavior during execution.
Error: A function call in method _ZN14spl_token_20229extension21confidential_transfer12verify_proof30verify_transfer_with_fee_proof17h1150fb2913991c8dE overwrites values in the frame. Please, decrease stack usage or remove parameters from the call.The …
```
=> 📝 Removing anchor-spl v0.30.1 from example

.github/workflows/run-tests.yml, package.json
| Ready | Tooling | No | None |
CI is failing because ephemeral-validator isn't globally installed
Install it globally
=> :white_check_mark: Globally installing ephemeral-validator

README.md
| Ready | Docs | No | None |
People with old version of nightly Rust toolchain will face this error
```rust
error[E0599]: no method named `file` found for reference `&proc_macro::Span` in the current scope
--> /home/username/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/proc-macro2-1.0.95/src/wrapper.rs:465:36
|
465 |             Span::Compiler(s) => s.file(),
|                                    ^^^^ method not found in `&Span`error[E0599]: no method named `local_file` found for reference `&proc_macro::Span` in the current scope
--> /home/username/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/proc-macro2-1.0.95/src/wrapper.rs:473:36
|
473 |             Span::Compiler(s) => s.local_file(),
| …
```
=> :memo: Adding latest nightly Rust toolchain as a requirement
